### ISSUE TITLE
javadoc task fails build

### ISSUE THREAD

**Issue by pauljarvis** [michaelruocco/wso2-test-containers#1] opened 2017-04-13 16:26 UTC
Just cloned the repo and the below error is returned when running `./gradlew clean build`
```
Execution failed for task ':javadoc'.
> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/home/engineer/git/michaelruocco/wso2-test-containers/build/tmp/javadoc/javadoc.options'
```  
Javadoc.options file is below, there's nothing obvious I can see going wrong.
[javadoc.options.txt](https://github.com/michaelruocco/wso2-test-containers/files/920247/javadoc.options.txt)

**Comment by michaelruocco** [comment] 2017-04-14 14:41
I worked through this with Paul, for anyone else coming across the problem it was caused by the environment he was using not having the javadoc executable available. I am going to close the issue but wanted to post this here incase anyone else runs into the same issue with their environment.

**Closed as completed by michaelruocco** 2017-04-14 14:41 UTC
